version: 0.2

env:
  variables:
    BUCKET: "sam-nascit"
    AWS_REGION: "us-west-2"
    STACK_NAME: "temp-units-conv-layer"

phases:
  install:
    commands:
      - echo "[Install phase]"
      - pip install -U pip
      - npm install -g npm@latest
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
      - pip install aws-sam-cli
      - sam --version
      # Install dependencies needed for running tests
      - cd NodeJS/temp-units-conv-layer && npm install && npm audit
      # Install 'temp-units-conv' library
      - cd dependencies/nodejs && npm install && npm audit
    finally:
      - echo "[Install phase finished]"
  pre_build:
    commands:
      - echo "[Pre-build phase]"
      - echo "$AWS_REGION"
      - aws configure set default.region $AWS_REGION
      - cd ../..
      # Discover and run unit tests in the 'tests' directory
      - npm run test
    finally:
      - echo "[Pre-build phase finished]"
  build:
    commands:
      # Use AWS SAM to package ane deploy the application
      - sam package --template-file template.yaml --s3-bucket $BUCKET --output-template-file out.yaml --region $AWS_REGION
      - sam deploy --template-file ./out.yaml --stack-name $STACK_NAME --capabilities CAPABILITY_IAM --region $AWS_REGION

artifacts:
  type: zip
  files:
    - NodeJS/temp-units-conv-layer/out.yaml