AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: temp-units-conv Lambda layer
Parameters:
  AllowedPrincipal:
    Type: String
    Description: Account principal allowed to deploy this layer
    Default: '*'

Resources:
    TempConversionDepLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
          LayerName: temp-units-conv-layer
          Description: temp-units-conv library for AWS Lambda
          ContentUri: dependencies/
          CompatibleRuntimes:
            - nodejs6.10
            - nodejs8.10
          LicenseInfo: 'MIT'
          RetentionPolicy: Retain
    DeploymentPermission:
        Type: "AWS::Lambda::LayerVersionPermission"
        Properties:
          Action: lambda:GetLayerVersion
          LayerVersionArn: !Ref TempConversionDepLayer
          Principal: !Ref AllowedPrincipal
Outputs:
  LambdaLayer:
    Value: !Ref TempConversionDepLayer